### ISSUE TITLE
Android: ConnectivityChangedEventArgs.IsConnected and ConnectivityTypeChangedEventArgs.IsConnected not correct

### ISSUE THREAD

**Issue by andrew-zaslow-tangoe** [jamesmontemagno/ConnectivityPlugin#59]
## Bug 

Version Number of Plugin: 2.3.0
Device Tested On: Nexus 5.X (Android 7.1.1)
Simulator Tested On: none

### Expected Behavior

ConnectivityChanged event should fire on every connectivity change and ConnectivityTypeChangedEventArgs.IsConnected should be correct.

### Actual Behavior

ConnectivityChanged event is not always firing when connectivity changes and ConnectivityTypeChanged event is firing but its IsConnected value is sometimes wrong.

### Steps to reproduce the Behavior

1. Run test app on Nexus 5.X (Android 7.1.1)
2. Ensure that LTE is on and WiFi is off (this isn't strictly necessary but makes the problem occur more frequently)
3. "Start Listening" in the test app.
4. Toggle Airplane mode on and off
5. When registered for the ConnectivityChanged event it sometimes doesn't fire.  When registered for the ConnectivityTypeChanged event the IsConnected value is sometimes wrong.

After doing some debugging and adding extra logic it seems that the old way of determining connectivity using ActiveNetworkInfo returns the correct value immediately after receiving the broadcast.  The new way using GetAllNetworks/GetNetworkInfo sometimes returns "true" at first (when connectivity has been turned off) but if called again repeatedly it does eventually return "false" after a few tenths of a second.

I don't know if the fact that the GetAllNetworks/GetNetworkInfo doesn't return up to the second information like ActiveNetworkInfo does is is an Android issue or expected Android behavior.

**Comment by adeconsulting** [comment]
I'm using the Connectivity plugin v2.3.0 with Xamarin Forms v2.3.3.193 and Android API 23.3.0.

I've implemented the sample app for obtaining the device's capabilities from the Xamarin University course  XAM150 REST Web Services:

https://elearning.xamarin.com/forms/xam150/1-obtain-the-devices-network-capabilities/exercise1/assets/xam150-ex1-completed.zip

I tweaked the app slightly and added logging, because of inconsistencies I’m seeing.

Here are logs from running on a Samsung Galaxy S7 (Android 6.0.1).

Run the app with LTE and WiFi on.

[3/4/2017 2:38:41 PM] [App] OnStart entered
[3/4/2017 2:38:41 PM] [NetworkViewPage] OnAppearing - CrossConnectivity.Current is not null
[3/4/2017 2:38:41 PM] [NetworkViewPage] OnAppearing - 1: Cellular, 2: Cellular, 3: WiFi

Enable Airplane Mode:

[3/4/2017 2:41:58 PM] [App] HandleConnectivityChanged: IsConnected is False
[3/4/2017 2:41:58 PM] [App] HandleConnectivityChanged: launching NoNetworkPage
[3/4/2017 2:41:58 PM] [NoNetworkPage] Constructor
[3/4/2017 2:41:58 PM] [NetworkViewPage] OnDisappearing - CrossConnectivity.Current is not null
[3/4/2017 2:41:58 PM] [NoNetworkPage] OnAppearing
[3/4/2017 2:41:58 PM] [NetworkViewPage] UpdateNetworkInfo - IsConnected: False

Disable Airplane Mode:

[3/4/2017 2:42:35 PM] [App] HandleConnectivityChanged: IsConnected is True
[3/4/2017 2:42:35 PM] [App] HandleConnectivityChanged: launching NetworkViewPage
[3/4/2017 2:42:35 PM] [NetworkViewPage] Constructor
[3/4/2017 2:42:35 PM] [NoNetworkPage] OnDisappearing
[3/4/2017 2:42:35 PM] [NetworkViewPage] OnAppearing - CrossConnectivity.Current is not null
[3/4/2017 2:42:35 PM] [NetworkViewPage] OnAppearing - 1: Cellular, 2: Cellular

Issue:  why isn’t WiFi listed?

Disable WiFi:

Issue:  no app activity is logged!

Enable WiFi:

Issue:  no app activity is logged!

Exit app:

[3/4/2017 2:45:50 PM] [NetworkViewPage] OnDisappearing - CrossConnectivity.Current is not null

App started:

[3/4/2017 2:45:57 PM] [NetworkViewPage] Constructor
[3/4/2017 2:45:57 PM] [App] OnStart entered
[3/4/2017 2:45:57 PM] [NetworkViewPage] OnAppearing - CrossConnectivity.Current is not null
[3/4/2017 2:45:57 PM] [NetworkViewPage] OnAppearing - 1: Cellular, 2: Cellular, 3: WiFi

Note:  WiFi is now listed!

Disable WiFi:

Issue: no app activity is logged!

Here are the relevant files:

[App.xaml.cs.txt](https://github.com/jamesmontemagno/ConnectivityPlugin/files/818991/App.xaml.cs.txt)
[NetworkViewPage.cs.txt](https://github.com/jamesmontemagno/ConnectivityPlugin/files/818993/NetworkViewPage.cs.txt)
[NoNetworkPage.cs.txt](https://github.com/jamesmontemagno/ConnectivityPlugin/files/818994/NoNetworkPage.cs.txt)
[Utils.cs.txt](https://github.com/jamesmontemagno/ConnectivityPlugin/files/818995/Utils.cs.txt)

**Comment by jamesmontemagno** [comment]
Did you try the latest beta?

**Comment by gtbuchanan** [comment]
I can confirm the issue still occurs on the latest beta (2.4.0.70-beta). I'm running Android 7.0 on a Samsung Galaxy S8. The issue **does not** occur on my Samsung Galaxy S4 running Android 6.0.1.

Perhaps using `NetworkCallback` as mentioned [here](https://stackoverflow.com/a/36447866/1409101) would be more reliable?

**Comment by gtbuchanan** [comment]
I've implemented the following workaround and it seems to resolve my issue. I just register the below class with my DI container instead of the default `ConnectivityImplementation` when the device is running Android N or greater:

```
/// <see href="https://github.com/jamesmontemagno/ConnectivityPlugin/issues/59">Workaround for GitHub issue 59</see>
/// <see href="https://developer.android.com/about/versions/nougat/android-7.0-changes.html#bg-opt">Android background optimizations</see>
[SuppressMessage("ReSharper", "ClassNeverInstantiated.Global", Justification = "Instantiated via dependency injection")]
internal sealed class Connectivity : ConnectivityImplementation
{
    public Connectivity()
    {
        var connectivityManager = (ConnectivityManager)Application.Context.GetSystemService(Context.ConnectivityService);
        var monitor = new ConnectionStateMonitor(this, OnConnectivityChanged);
        monitor.Register(connectivityManager);
    }

    /// <see href="https://stackoverflow.com/a/36447866/140910">Adapted from StackOverflow</see>
    private sealed class ConnectionStateMonitor : ConnectivityManager.NetworkCallback
    {
        private IConnectivity Connectivity { get; }

        private Action<ConnectivityChangedEventArgs> Changed { get; }

        private NetworkRequest Request { get; }

        public ConnectionStateMonitor(IConnectivity connectivity, Action<ConnectivityChangedEventArgs> changed)
        {
            Connectivity = connectivity;
            Changed = changed;
            Request = new NetworkRequest.Builder()
                .AddTransportType(TransportType.Cellular)
                .AddTransportType(TransportType.Wifi)
                .Build();
        }

        public void Register(ConnectivityManager manager) => manager.RegisterNetworkCallback(Request, this);

        public override void OnAvailable(Network network) => Changed?.Invoke(new ConnectivityChangedEventArgs { IsConnected = Connectivity.IsConnected });

        public override void OnLost(Network network) => Changed?.Invoke(new ConnectivityChangedEventArgs { IsConnected = Connectivity.IsConnected });
    }
}
```

**Comment by jamesmontemagno** [comment]
I could not reproduce this at all on my 6P to be honest with you. I think that probably a small delay needs to be put in (same that I do on iOS) before checking it.
